version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./:/go/src
    tty: true

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ach
      MYSQL_USER: ach
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
